# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [ '--unsafe' ]
      - id: check-shebang-scripts-are-executable
      - id: check-vcs-permalinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        language_version: '3.11'
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.3.0
    hooks:
      - id: pycln
        args: [--all]
exclude: ^tests/snapshot_tests
