site_name: Textual
site_url: https://www.textualize.io/

nav:
  - "index.md"
  - "getting_started.md"
  - "introduction.md"
  - Guide:
    - "guide/devtools.md"
    - "guide/CSS.md"
    - "guide/events.md"

  - "actions.md"
  - Events:
    - "events/blur.md"
    - "events/descendant_blur.md"
    - "events/descendant_focus.md"
    - "events/enter.md"
    - "events/enter.md"
    - "events/focus.md"
    - "events/hide.md"
    - "events/key.md"
    - "events/leave.md"
    - "events/load.md"
    - "events/mount.md"
    - "events/mouse_capture.md"
    - "events/mouse_click.md"
    - "events/mouse_down.md"
    - "events/mouse_move.md"
    - "events/mouse_release.md"
    - "events/mouse_scroll_down.md"
    - "events/mouse_scroll_up.md"
    - "events/mouse_up.md"
    - "events/paste.md"
    - "events/resize.md"
    - "events/screen_resume.md"
    - "events/screen_suspend.md"
    - "events/show.md"
  - Styles:
    - "styles/background.md"
    - "styles/border.md"
    - "styles/box_sizing.md"
    - "styles/color.md"
    - "styles/content_align.md"
    - "styles/display.md"
    - "styles/height.md"
    - "styles/layout.md"
    - "styles/margin.md"
    - "styles/max_height.md"
    - "styles/max_width.md"
    - "styles/min_height.md"
    - "styles/min_width.md"
    - "styles/offset.md"
    - "styles/outline.md"
    - "styles/overflow.md"
    - "styles/padding.md"
    - "styles/scrollbar.md"
    - "styles/scrollbar_gutter.md"
    - "styles/scrollbar_size.md"
    - "styles/text_align.md"
    - "styles/text_style.md"
    - "styles/tint.md"
    - "styles/visibility.md"
    - "styles/width.md"
  - Widgets: "/widgets/"
  - Reference:
    - "reference/app.md"
    - "reference/color.md"
    - "reference/dom_node.md"
    - "reference/events.md"
    - "reference/geometry.md"
    - "reference/message_pump.md"
    - "reference/timer.md"
    - "reference/widget.md"


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - admonition
  - def_list
  - meta

  - toc:
      permalink: true
      baselevel: 1
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: textual
          class: textual
          format: !!python/name:textual._doc.format_svg
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - markdown.extensions.attr_list

theme:
  name: material
  custom_dir: custom_theme
  # features:
  #   - navigation.tabs
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    toggle:
      icon: material/weather-night
      name: Switch to light mode

plugins:

- search:
- autorefs:
- mkdocstrings:
    default_handler: python
    handlers:
        python:
          rendering:
            show_source: false
          selection:
            filters:
              - "!^_"
              - "^__init__$"
              - "!^can_replace$"

    watch:
      - src/textual


extra_css:
  - stylesheets/custom.css
