[tool.poetry]
name = "textual"
version = "0.1.15"
homepage = "https://github.com/Textualize/textual"
description = "Text User Interface using Rich"
authors = ["Will McGugan <willmcgugan@gmail.com>"]
license = "MIT"
classifiers = [
    "Development Status :: 1 - Planning",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

[tool.poetry.scripts]
textual = "textual.cli.cli:run"

[tool.poetry.dependencies]
python = "^3.7"
rich = "^12.0.0"

#rich = {git = "git@github.com:willmcgugan/rich", rev = "link-id"}
typing-extensions = { version = "^3.10.0", python = "<3.8" }
click = "8.1.2"
importlib-metadata = "^4.11.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
black = "^22.3.0"
mypy = "^0.950"
pytest-cov = "^2.12.1"
mkdocs = "^1.2.3"
mkdocstrings = "^0.17.0"
mkdocs-material = "^7.3.6"
pre-commit = "^2.13.0"
pytest-aiohttp = "^1.0.4"
time-machine = "^2.6.0"

[tool.black]
includes = "src"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
